javaonline/views/home/controllers.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__, template_folder='templates')

@home_bp.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

javaonline/views/login/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from javaonline.models.login_form import LoginForm
from javaonline.models.user import User
from javaonline.db.base import Session

from flask_login import login_user, logout_user, current_user

session = Session()

login_bp = Blueprint('login', __name__, template_folder='templates')

@login_bp.route('/login', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('challenges.index'))

    form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', form=form)
    elif form.validate_on_submit():

        user = session.query(User).filter(User.username == form.username.data).first()

        if user == None or not user.check_password(form.password.data):
            form.submit.errors.append('Username or password is incorrect')
            # return redirect(url_for('login.index'))
            return render_template('login.html', form=form)

        login_user(user)
        return redirect(url_for('challenges.index'))

        # flash('Welcome back, {}'.format(form.username.data))

@login_bp.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('login.index'))

javaonline/views/register/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from javaonline.models.register_form import RegisterForm
from javaonline.models.user import User
from javaonline.models.role import Role
from javaonline.db.base import Session

from datetime import datetime

from flask_login import login_user, logout_user, current_user

session = Session()

register_bp = Blueprint('register', __name__, template_folder='templates')

@register_bp.route('/register', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('challenges.index'))

    form = RegisterForm()
    if request.method == 'GET':
        return render_template('register.html', form=form)
    elif form.validate_on_submit():
        role = Role('user')

        user = User(username=form.username.data, email=form.email.data, password=form.password.data, role=role)

        user.set_experience_points(0)
        user.set_created_on(datetime.now())
        user.set_last_login(None)

        session.add(user)
        session.commit()
        session.close()

        return redirect(url_for('login.index'))

        # flash('Welcome back, {}'.format(form.username.data))
    return render_template('register.html', form=form)

javaonline/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        html {
            position: relative;
            min-height: 100%;
        }

        body {
            padding-top: 5rem;
            margin-bottom: 60px;
        }

        .starter-template {
            padding: 3rem 1.5rem;
            text-align: center;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 60px;
            /* Set the fixed height of the footer here */
            line-height: 60px;
            /* Vertically center the text there */
            background-color: #28a745;
        }
    </style>
    <style type="text/css" media="screen">
    #editor, #editor2 { 
        position: relative;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        min-height: 400px;
    }
    #output {
        min-height: 250px;
        background-color: black;
        color: #DEDEDE;
    }
</style>
    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/highlight.min.js"></script>
    <title>Java Online</title>
</head>

<body class="bg-light">
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{{ url_for('home.index') }}">Java Online</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('challenges.index') }}">Challenges</a>
                </li>
            </ul>
            <div class="my-2 my-lg-0">
                {% if current_user.is_authenticated %}
                    <ul class="navbar-nav mr-auto" style="min-width: 100px;">
                        <li class="nav-item dropdown w-100 text-right">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ current_user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="min-width:100px">
                                <button type="button" class="btn btn-link"><a href="{{ url_for('login.logout') }}">Logout</a></button>
                            </div>
                        </li>
                        
                    </ul>
                    
                {% else %}
                    <button type="button" class="btn btn-link"><a href="{{ url_for('login.index') }}">Login</a></button>
                    <button type="button" class="btn btn-success"><a href="{{ url_for('register.index') }}" style="color:inherit;">Register</a></button>
                {% endif %}
                
            </div>
        </div>
    </nav>

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div aria-live="polite" aria-atomic="true" style="position: relative;">
                        <div class="toast" style="position: absolute; top: 0; right: 1rem; min-width: 200px;">
                            <div class="toast-header">
                                <strong class="mr-auto">{{ message }}</strong>
                                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

    <main role="main" class="container">

        {% block body %}{% endblock %}


    </main>

    <footer class="footer">
        <div class="container">
            <span style="color: white;">Copyright &copy; Toby Cook 2020</span>
        </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <script>
        $('.toast').toast({delay:5000});
        $('.toast').toast('show');
    </script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="../static/ace/ace.js" type="text/javascript" charset="utf-8"></script>
    <script src="../static/js/encode.js" type="text/javascript" charset="utf-8"></script>
    <script>
        var editor = ace.edit("editor", {
            mode: "ace/mode/java"
        });
        editor.setTheme("ace/theme/xcode");
        var editor2 = ace.edit("editor2", {
            mode: "ace/mode/java"
        });
        editor2.setTheme("ace/theme/xcode");
        var output = ace.edit("output", {
            mode: "ace/mode/text"
        });
        output.setTheme("ace/theme/terminal");
        output.setReadOnly(true);
        output.setHighlightActiveLine(false);
        output.setShowPrintMargin(false);
    </script>
</body>

</html>